name: Check updates
on:
  pull_request:
    branches:
      - main

jobs:
  outdater:
    runs-on: ubuntu-latest
    name: Dependencies outdater
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Dependencies Outdater
        uses: action-runner/dependencies-outdater@master
        with:
          access_token: ${{ secrets.RELEASE_TOKEN }}
          package_manager: pnpm
